ERROR - 2021-11-11 17:34:08 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2021-11-11 17:34:08 --> Unable to connect to the database.
#0 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Model.php(213): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\BaseModel.php(583): CodeIgniter\Model->doFindAll(3, 0)
#4 C:\xampp\htdocs\syifa_hidroponik\app\Models\BlogpostModel.php(23): CodeIgniter\BaseModel->findAll(3)
#5 C:\xampp\htdocs\syifa_hidroponik\app\Controllers\Home.php(29): App\Models\BlogpostModel->getBlogpost3()
#6 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(873): App\Controllers\Home->index()
#7 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(408): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(319): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\syifa_hidroponik\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2021-11-11 17:34:08 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\syifa_hidroponik\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\syifa_hidroponik\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Home), true)
#2 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Debug\Exceptions.php(281): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-11-11 17:45:39 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2021-11-11 17:45:39 --> Unable to connect to the database.
#0 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Model.php(836): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\syifa_hidroponik\app\Models\AdminModel.php(27): CodeIgniter\Model->__call('get', Array)
#4 C:\xampp\htdocs\syifa_hidroponik\app\Controllers\Admin.php(37): App\Models\AdminModel->ceklogin('10118300', 'ads')
#5 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(873): App\Controllers\Admin->ceklogin()
#6 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(408): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin))
#7 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(319): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\syifa_hidroponik\public\index.php(44): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2021-11-11 17:45:39 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\syifa_hidroponik\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\syifa_hidroponik\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Admin), true)
#2 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Debug\Exceptions.php(281): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
CRITICAL - 2021-11-11 18:57:09 --> Invalid file: /home/detail-ordere.php
#0 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\View\View.php(203): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/home/detail-or...')
#1 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('/home/detail-or...', Array, true)
#2 C:\xampp\htdocs\syifa_hidroponik\app\Controllers\Cart.php(51): view('/home/detail-or...', Array)
#3 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(873): App\Controllers\Cart->detailorder()
#4 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(408): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cart))
#5 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(319): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\syifa_hidroponik\public\index.php(44): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#8 {main}
CRITICAL - 2021-11-11 18:57:44 --> Invalid file: /home/detail-ordere.php
#0 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\View\View.php(203): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('/home/detail-or...')
#1 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Common.php(1217): CodeIgniter\View\View->render('/home/detail-or...', Array, true)
#2 C:\xampp\htdocs\syifa_hidroponik\app\Controllers\Cart.php(51): view('/home/detail-or...', Array)
#3 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(873): App\Controllers\Cart->detailorder()
#4 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(408): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Cart))
#5 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(319): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\xampp\htdocs\syifa_hidroponik\public\index.php(44): CodeIgniter\CodeIgniter->run()
#7 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#8 {main}
ERROR - 2021-11-11 19:00:02 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2021-11-11 19:00:02 --> Unable to connect to the database.
#0 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\syifa_hidroponik\app\Models\ProdukModel.php(18): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\syifa_hidroponik\app\Controllers\Home.php(43): App\Models\ProdukModel->getProduk()
#4 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(873): App\Controllers\Home->product()
#5 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(408): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#6 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(319): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\xampp\htdocs\syifa_hidroponik\public\index.php(44): CodeIgniter\CodeIgniter->run()
#8 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#9 {main}
CRITICAL - 2021-11-11 19:00:02 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\syifa_hidroponik\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\syifa_hidroponik\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Home), true)
#2 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Debug\Exceptions.php(281): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
ERROR - 2021-11-11 19:33:42 --> Error connecting to the database: No connection could be made because the target machine actively refused it.

CRITICAL - 2021-11-11 19:33:42 --> Unable to connect to the database.
#0 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\BaseConnection.php(620): CodeIgniter\Database\BaseConnection->initialize()
#1 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1866): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#2 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Model.php(213): CodeIgniter\Database\BaseBuilder->get()
#3 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\BaseModel.php(583): CodeIgniter\Model->doFindAll(0, 0)
#4 C:\xampp\htdocs\syifa_hidroponik\app\Models\BlogpostModel.php(15): CodeIgniter\BaseModel->findAll()
#5 C:\xampp\htdocs\syifa_hidroponik\app\Controllers\Home.php(82): App\Models\BlogpostModel->getBlogpost()
#6 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(873): App\Controllers\Home->blog()
#7 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(408): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\CodeIgniter.php(319): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\syifa_hidroponik\public\index.php(44): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\xampp\\htdocs...')
#11 {main}
CRITICAL - 2021-11-11 19:33:42 --> Uncaught ErrorException: print_r(): Property access is not allowed yet in C:\xampp\htdocs\syifa_hidroponik\app\Views\errors\html\error_exception.php:100
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'print_r(): Prop...', 'C:\\xampp\\htdocs...', 100, Array)
#1 C:\xampp\htdocs\syifa_hidroponik\app\Views\errors\html\error_exception.php(100): print_r(Object(App\Controllers\Home), true)
#2 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Debug\Exceptions.php(281): include('C:\\xampp\\htdocs...')
#3 C:\xampp\htdocs\syifa_hidroponik\vendor\codeigniter4\framework\system\Debug\Exceptions.php(147): CodeIgniter\Debug\Exceptions->render(Object(CodeIgniter\Database\Exceptions\DatabaseException), 500)
#4 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(CodeIgniter\Database\Exceptions\DatabaseException))
#5 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
